#!/usr/bin/perl
#
# Leon: I have run into a design problem with crypt passwords that I somehow
#       didn't see coming (epic doh!). Crypt salts + challenge/response for auth.
#       I'm leaving crypt passwords for now. 
#
# Simple management for OpenFPC users and passwords.
#
#########################################################################################
# Copyright (C) 2010 Leon Ward 
# openfpc-passwd - Part of the OpenFPC - (Full Packet Capture) project
#
# Contact: leon@openfpc.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#########################################################################################

use strict;
use warnings;
use Data::Dumper;
use Switch;
use Term::ReadKey;
use File::Copy;
use Getopt::Long;

my %users=();
my $update=0;
my $action=0;
my $file=0;
my $user=0;
my $showhelp;

sub showhelp{
	print "
Usage: openfpc-passwd <args>
  -a or --action           One of add / change / list / del / check
  -u or --user             Username to take --action on
  -f or --file             User file to edit

Note: backups are taken if any changes are made.
";
	exit 0;
}

GetOptions (    'a|action=s' => 	\$action,
		'u|username=s' => 	\$user,
		'f|file|config=s' => 	\$file,
		'h|help' => 		\$showhelp,
);

showhelp if $showhelp;

die("Error: Must specify filename. See --help\n") unless $file;

#unless ($> == 0 || $< == 0) { die "You need root privs to run this tool.\n" }

if ( -f $file ) {
       	open FILE, '<', "$file" or die "Unable to open config file $file $!";
       	while(my $line=<FILE>) {
               	chomp $line;
		if ($line =~ /^OFPC_ENABLED/ ) {
			die("This Looks like this is an OpenFPC config file, not a user file. \nWont continue.\n");
		}

	        if ( $line =~ m/^[a-zA-Z]/) {
 	 		(my $key, my @value) = split /:/, $line;
               	        $users{$key} = $value[0];
               	}	   
       	}   
       	close(FILE);
} else {
	print "Creating new user file $file...\n";
}

switch($action) {
	case "add" {
		die("Must specify username. See --help\n") unless $user;

		unless ( defined $users{$user}) {
			print "Adding user $user\n";
			print "Enter new password for $user :";
			ReadMode 'noecho';
			my $pass = ReadLine 0;
			chomp $pass;	
			ReadMode 'normal';
			my $salt=join '', ('.', '/', 0..9, 'A'..'Z', 'a'..'z')[rand 64, rand 64];
			my $cryptpass=crypt($pass,$salt);
			$users{$user}=$cryptpass;
			$update=1;
		} else {
			die("User $user already exists\n");
		}
	}
	case "delete"{
		die("Must specify username. See --help\n") unless $user;

		if (defined $users{$user}) {
			delete $users{$user};
			$update=1;
		} else {
			die("Cant find user in $file\n");
		}
	}
	case "list" {
		print "* User List in $file\n";
		foreach (keys %users) {
			print "User $_ Pass $users{$_}\n";
		}
	}
	case "change" {
		die("Must specify username. See --help\n") unless $user;

		if ( defined $users{$user}) {
			print "Enter new password for $user :";
			ReadMode 'noecho';
			my $pass = ReadLine 0;
			chomp $pass;	
			ReadMode 'normal';
			my $salt=join '', ('.', '/', 0..9, 'A'..'Z', 'a'..'z')[rand 64, rand 64];
			my $cryptpass=crypt($pass,$salt);
			$users{$user}=$cryptpass;
			$update=1;
		} else {
			die("User $user not found in $file\n");
		}
	}
	case "check" {
		die("Must specify username. See --help\n") unless $user;

		# Check a password against a stored value
		if ( defined $users{$user}) {
			print "Enter password for $user :";
			ReadMode 'noecho';
			my $pass = ReadLine 0;
			chomp $pass;	
			ReadMode 'normal';
			if (crypt($pass, $users{$user}) eq $users{$user}) {
				print "Password correct\n";
			} else {
				print "Password incorrect\n";
			}
		} else {
			die("User $user not found in $file\n");
		}
	} else {
		die("Invalid action \"$action\"\n");
	}
}

if ($update) {
	# If we have added or changed a value in the user hash, lets write it back to the file 
	# while also creating a backup.
	# Backup existing config, and replace it with our new file.
	my $epoch=time();
	if ( -f $file) {
        		move($file,"$file.backup.$epoch") or die ("ERROR: Unable to backup $file to $file.backup.$epoch - Check file permissions\n");
	}

	open(NEWFILE,'>', "$file") or die("ERROR: Can't open file $file");
	print NEWFILE "########################################\n";
	print NEWFILE "# OpenFPC User file.\n# This file is autogenerated. Do not edit\n";

	foreach (keys %users){
		print NEWFILE "$_:$users{$_}\n";
	}
	close(NEWFILE);
	print "\nDone.\n";
}
