#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          openfpc-restapi
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A Rest API interface to OpenFPC
# Description:       Interact with OpenFPC via a standard API
### END INIT INFO

# Leon Ward - leon@openfpc.org

IAM=`whoami`
DIR="/opt/openfpc-restapi"
USER="openfpc"
GROUP="openfpc"
PIDDIR="/var/run/"
PIDFILE="ofpcapi.pid"
DESC="OpenFPC Rest API"
CWD="/opt/ofpcapi"
PORT="4222"
SSL_CERT="/etc/openfpc/ofpcapi.cert.pem"
SSL_KEY="/etc/openfpc/ofpcapi.key.pem"
DEBUG=1

IAM=`whoami`;

die(){
  echo $1
  exit 1
}

[ -f /lib/lsb/init-functions ] && . /lib/lsb/init-functions

if [ "$IAM" != "root" ]; then
    die "[!] Must be root to run this script"
fi
 
start()
{
    log_daemon_msg "Starting" "$DESC"
    cd $CWD
    # create empty log fir
    [ -d logs ]  || mkdir logs
    chown $USER:$GROUP logs

    CMD="/usr/bin/starman \
        -D \
        --workers 2 \
        --port $PORT \
        --pid $PIDDIR/$PIDFILE \
        -E production \
        --user $USER \
        --group $GROUP \
        --ssl-cert $SSL_CERT \
        --ssl-key $SSL_KEY \
        --enable-ssl \
        ./bin/app.psgi "

    if [ "$DEBUG" == "1" ]
    then
        echo $CMD
    else 
        exec $CMD    
    fi


    if [ $? != 0 ]; then
        log_end_msg 1
        exit 1
    else
        log_end_msg 0
    fi
}

stop()
{
    if [ "$IAM" != "root" ]; then
        die "[!] Must be root to run this script"
    fi

    log_daemon_msg "Stopping $DESC"
    if [ -e $PIDDIR/$PIDFILE ]
    then

       PID=$(cat $PIDDIR/$PIDFILE)
       kill $PID
       log_end_msg 0
    else
        log_end_msg 1
    fi
} 

case "$1" in
    start)
        start
    ;;
 
    force-start)
        start
    ;;
   
    force-stop)
        stop
    ;;
 
    stop)
        stop
    ;;
 
    restart)
        stop
        start
    ;;

    reload)
        stop
        start
    ;; 

    *)
        echo "Usage: /etc/init.d/openfpc-restapi {start|stop|force-stop|reload|restart}"
        exit 1
    ;;
esac
 
exit 0

