#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          openfpc-cx2db
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Loads sessions into DB
# Description:       This is perl deamon to load session data
#                    into a MySQL database.
### END INIT INFO

# Check if we have been passed a config file as $2.
# read the first config file found in order above.
CONFIG_FILES="/etc/openfpc/openfpc.conf"

if [ $2 ]; then
   if [ -f $2 ]; then
      CONFIG=$2
      echo "[*] Reading configuration file $CONFIG"
      source $CONFIG
   else
      echo -e "[!] Error: Cant find config file $CONFIG"
      exit 1
   fi
else
   for CONFIG in $CONFIG_FILES; do
      if [ -f $CONFIG ]; then
         echo "[*] Reading configuration file $CONFIG"
         source $CONFIG
         break
      fi
   done
fi

function die() {
   echo $1
   exit 1
}

# We'll add up all the options above and use them
NAME=ofpc-cx2db
DAEMON=`which ofpc-cx2db.pl` || die "[!] $NAME program not found in path."
PIDFILE=$NAME-$NODENAME.pid
PIDPATH=/var/run
LOG_FILE=/var/log/$NAME.log

stopproc() {
  echo -n "Stopping $NAME ..."
  if [ -f $PIDPATH/$PIDFILE ]; then
    kill `cat $PIDPATH/$PIDFILE` >$LOG_FILE
    if [ $? = 0 ]; then
      echo "Success."
      rm -vf $PIDPATH/$PIDFILE >$LOG_FILE
    else
      kill -9 `cat $PIDPATH/$PIDFILE` >$LOG_FILE
      if [ $? = 0 ]; then
         echo "Success."
         rm -vf $PIDPATH/$PIDFILE >$LOG_FILE
      else
         echo "Failed."
      fi
    fi
  fi
}

startproc() {
   if [ -f $PIDPATH/$PIDFILE ]; then
       CXPID=$(cat $PIDPATH/$PIDFILE)
       if ps $CXPID > /dev/null; then
          echo -e  "[!] $NAME already running with pid: $CXPID"
          exit 1
       fi
    fi
    rm -vf $PIDPATH/$PIDFILE >$LOG_FILE
    echo "[*] Starting $NAME (Loads cxtracker sessions into DB)"
    $DAEMON --daemon --config $CONFIG >$LOG_FILE
    echo " done."
}

# See how we were called.
case "$1" in
  start)
        startproc
	;;
  stop)
        stopproc
	;;
  status)
        # Show the rules and counters
	if [ -s $PIDPATH/$PIDFILE ]; then
	  echo -n "$NAME running with PID: "
          cat $PIDPATH/$PIDFILE
	  #echo -n "Dumping $NAME stats"
	  #kill -USR1 `cat $PIDFILE`
          #echo " done."
	else 
	  echo "$NAME not running!"
        fi
	;;
  restart)
        stopproc
        startproc
        ;;
  force-reload)
        stopproc
        startproc
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status|force-reload}"
        exit 1
esac

exit 0
